[build]
  # Wir nutzen den relativen Pfad zu Flutter (./flutter/bin/flutter), 
  # damit wir die PATH-Variable nicht anfassen mÃ¼ssen.
  command = "git clone https://github.com/flutter/flutter.git -b stable && ./flutter/bin/flutter build web --release"
  
  publish = "build/web"